import { App, ItemView, MarkdownView, Menu, Modal, Notice, Setting, TFile, WorkspaceLeaf, normalizePath } from "obsidian";
import { getSettingsCopy } from "./i18n";
import type TaskManagerPlugin from "./main";
import { appendDoneToken, appendTaskComment, parseTaskLine, setTaskPriority, stripMetadataTokens } from "./tasks/task-line";
import type { TaskPriority } from "./types";
import { getCurrentTimestamp, getDatePart } from "./utils/date";

export const TASK_SIDEBAR_VIEW_TYPE = "task-manager-sidebar-view";
type PriorityFilter = TaskPriority | "all";
type ArchiveFilter = "all" | "active" | "archived";
type StatusFilter = "all" | "open" | "done";

type SidebarTask = { file:TFile; lineNumber:number; text:string; checked:boolean; date:string|null; priority:TaskPriority; archived:boolean; comments:string[]; startToken?:string; doneToken?:string; };
type SidebarFilters = { filePath:string; startDate:string; endDate:string; priority:PriorityFilter; archive:ArchiveFilter; status:StatusFilter };

export class TaskSidebarView extends ItemView {
  private filePathInputEl?: HTMLInputElement; private statusEl?: HTMLElement; private taskListEl?: HTMLElement;
  private startDateInputEl?: HTMLInputElement; private endDateInputEl?: HTMLInputElement; private prioritySelectEl?: HTMLSelectElement; private archiveSelectEl?: HTMLSelectElement; private statusSelectEl?: HTMLSelectElement; private pathSuggestEl?: HTMLDataListElement;
  private tasks: SidebarTask[] = [];
  constructor(leaf: WorkspaceLeaf, private readonly plugin: TaskManagerPlugin){ super(leaf);} getViewType(){return TASK_SIDEBAR_VIEW_TYPE;} getDisplayText(){return this.copy.taskSidebarTitle;} getIcon(){return "list-checks";}
  async onOpen(){this.render(); await this.refreshTasks(); this.registerEvent(this.app.vault.on("modify",()=>void this.refreshTasks())); this.registerEvent(this.app.vault.on("create",()=>void this.refreshTasks())); this.registerEvent(this.app.vault.on("delete",()=>void this.refreshTasks()));}
  async onClose(){this.containerEl.empty();}

  private render(){ const c=this.containerEl.children[1]; c.empty(); c.addClass("task-manager-sidebar"); c.createEl("h3",{text:this.copy.taskSidebarTitle});
    const controls=c.createDiv({cls:"task-manager-sidebar-controls"}); controls.createEl("label",{text:this.copy.taskSidebarFilePathLabel});
    const id=`task-path-${Date.now()}`; this.pathSuggestEl=controls.createEl("datalist"); this.pathSuggestEl.id=id;
    this.filePathInputEl=controls.createEl("input",{type:"text",cls:"task-manager-sidebar-file-filter",attr:{list:id,placeholder:this.copy.taskSidebarFilePathPlaceholder}});
    this.filePathInputEl.addEventListener("input",()=>{this.refreshPathSuggestions(); void this.refreshTasks();});
    const row=controls.createDiv({cls:"task-manager-sidebar-select-row"});
    const s1=row.createDiv(); s1.createEl("label",{text:this.copy.taskSidebarArchiveFilter}); this.archiveSelectEl=s1.createEl("select"); [["all",this.copy.taskSidebarAllTasks],["active",this.copy.taskSidebarNotArchived],["archived",this.copy.taskSidebarArchived]].forEach(([v,t])=>this.archiveSelectEl!.createEl("option",{value:v,text:t})); this.archiveSelectEl.value="active"; this.archiveSelectEl.onchange=()=>void this.refreshTasks();
    const s2=row.createDiv(); s2.createEl("label",{text:"Status"}); this.statusSelectEl=s2.createEl("select"); [["all","All"],["open","Open"],["done","Done"]].forEach(([v,t])=>this.statusSelectEl!.createEl("option",{value:v,text:t})); this.statusSelectEl.onchange=()=>void this.refreshTasks();
    const s3=row.createDiv(); s3.createEl("label",{text:this.copy.taskSidebarPriority}); this.prioritySelectEl=s3.createEl("select"); [["all",this.copy.taskSidebarAllPriorities],["urgent",this.copy.taskSidebarPriorityUrgent],["high",this.copy.taskSidebarPriorityHigh],["medium",this.copy.taskSidebarPriorityMedium],["low",this.copy.taskSidebarPriorityLow],["none",this.copy.taskSidebarPriorityNone]].forEach(([v,t])=>this.prioritySelectEl!.createEl("option",{value:v,text:t})); this.prioritySelectEl.onchange=()=>void this.refreshTasks();
    const d=controls.createDiv({cls:"task-manager-sidebar-date-range"}); this.startDateInputEl=d.createEl("input",{type:"date"}); this.endDateInputEl=d.createEl("input",{type:"date"}); this.startDateInputEl.onchange=()=>void this.refreshTasks(); this.endDateInputEl.onchange=()=>void this.refreshTasks();
    this.statusEl=c.createDiv({cls:"task-manager-sidebar-status"}); this.taskListEl=c.createDiv({cls:"task-manager-sidebar-list"});
    this.refreshPathSuggestions();
  }
  private refreshPathSuggestions(){ if(!this.pathSuggestEl) return; const q=(this.filePathInputEl?.value||"").toLowerCase(); this.pathSuggestEl.empty(); const paths=[...new Set(this.app.vault.getMarkdownFiles().map(f=>{const i=f.path.lastIndexOf('/'); return i>0?f.path.slice(0,i):"/";}))].sort(); paths.filter(p=>!q||p.toLowerCase().includes(q)).slice(0,40).forEach(p=>this.pathSuggestEl!.createEl("option",{value:p}));}
  private getFilters():SidebarFilters{return{filePath:this.filePathInputEl?.value.trim()??"",startDate:this.startDateInputEl?.value??"",endDate:this.endDateInputEl?.value??"",priority:(this.prioritySelectEl?.value as PriorityFilter)??"all",archive:(this.archiveSelectEl?.value as ArchiveFilter)??"active",status:(this.statusSelectEl?.value as StatusFilter)??"all"};}
  private async refreshTasks(){ this.tasks=await this.collectTasks(); this.renderTasks(); }
  private renderTasks(){ if(!this.taskListEl||!this.statusEl) return; const f=this.getFilters(); const list=this.tasks.filter(t=>this.matchTask(t,f)); this.statusEl.setText(`${list.length} task(s)`); this.taskListEl.empty(); if(!list.length){this.taskListEl.createDiv({cls:"task-manager-sidebar-empty",text:this.copy.taskSidebarNoTasks}); return;} for(const t of list){const card=this.taskListEl.createDiv({cls:`task-manager-sidebar-task is-priority-${t.priority}${t.archived?" is-archived":""}`});
      const row=card.createDiv({cls:"task-manager-sidebar-task-row"}); const cb=row.createEl("input",{type:"checkbox"}); cb.checked=t.checked; cb.addEventListener("click",e=>e.stopPropagation()); cb.addEventListener("change",()=>void this.toggleDone(t,cb.checked));
      const title=row.createDiv({cls:"task-manager-sidebar-task-title",text:stripMetadataTokens(t.text)||this.copy.taskSidebarEmptyTask}); if(t.checked) title.addClass("is-done");
      const meta=card.createDiv({cls:"task-manager-sidebar-task-meta"}); const parts=[t.file.path,t.checked?"done":"open"]; if(t.date) parts.push(t.date); if(t.archived) parts.push(this.copy.taskSidebarArchivedStatus); if(t.startToken&&t.doneToken&&t.archived) parts.push(this.formatDuration(t.startToken,t.doneToken)); meta.setText(parts.join(" · "));
      for(const cm of t.comments){card.createDiv({cls:"task-manager-sidebar-comment",text:stripMetadataTokens(cm)});} card.onclick=()=>void this.openTask(t); card.oncontextmenu=(e)=>{e.preventDefault(); this.openTaskMenu(t,e as MouseEvent);};
    }}
  private matchTask(t:SidebarTask,f:SidebarFilters){ const p=normalizePath(f.filePath||"").replace(/\/$/,""); if(p && !(normalizePath(t.file.path)===p || normalizePath(t.file.path).startsWith(p+"/"))) return false; if(f.archive==="active"&&t.archived) return false; if(f.archive==="archived"&&!t.archived) return false; if(f.status==="open"&&t.checked) return false; if(f.status==="done"&&!t.checked) return false; if(f.priority!=="all"&&t.priority!==f.priority) return false; if((f.startDate||f.endDate)&&t.date){ if(f.startDate&&t.date<f.startDate) return false; if(f.endDate&&t.date>f.endDate) return false;} return !(f.startDate||f.endDate) || !!t.date; }
  private async collectTasks(){ const out:SidebarTask[]=[]; for(const file of this.app.vault.getMarkdownFiles()){ const lines=(await this.app.vault.cachedRead(file)).split("\n"); for(let i=0;i<lines.length;i++){ const p=parseTaskLine(lines[i]); if(!p) continue; const comments:string[]=[]; for(let j=i+1;j<lines.length;j++){const m=/^\s*-\s+(.*?)\s*@comment/.exec(lines[j]); if(!m) break; comments.push(m[1]); }
      out.push({file,lineNumber:i,text:p.body,checked:p.checked,date:getDatePart((p.doneToken??p.startToken??"").replace(/^@\w+\(|\)$/g,""))??null,priority:p.priority,archived:/@archived\([^)]+\)/.test(p.body),comments,startToken:p.startToken,doneToken:p.doneToken}); }} return out; }
  private async toggleDone(task:SidebarTask,checked:boolean){ const token=this.plugin.settings.doneTokenFormat.replace("{date}",getCurrentTimestamp(this.plugin.settings.timestampPrecision)); await this.updateTaskLine(task,line=>{ if(checked){return appendDoneToken(line,token);} return line.replace(/\s*@done\([^)]+\)/," ").replace(/\s{2,}/g," ").replace("- [x]","- [ ]").trimEnd();}); }
  private openTaskMenu(task:SidebarTask,event:MouseEvent){ const menu=new Menu(); const sub=new Menu(); (["urgent","high","medium","low","none"] as TaskPriority[]).forEach((p)=>sub.addItem(i=>i.setTitle(this.copy.taskSidebarSetPriority(this.getPriorityLabel(p))).onClick(()=>void this.updateTaskLine(task,l=>setTaskPriority(l,p))))); menu.addItem(i=>{i.setTitle(this.copy.taskSidebarPriority).setIcon("flag"); (i as any).setSubmenu?.(sub); if(!(i as any).setSubmenu){i.onClick(e=>sub.showAtMouseEvent(e as MouseEvent));}}); menu.addItem(i=>i.setTitle(this.copy.taskSidebarAddComment).setIcon("message-square-plus").onClick(()=>new TaskCommentModal(this.app,this.plugin,async c=>this.updateTaskLine(task,l=>appendTaskComment(l,c, this.plugin.settings.timestampPrecision))).open())); menu.showAtMouseEvent(event); }
  private async updateTaskLine(task:SidebarTask,updater:(line:string)=>string){ await this.app.vault.process(task.file,(content)=>{const lines=content.split("\n"); if(lines[task.lineNumber]===undefined||!parseTaskLine(lines[task.lineNumber])){new Notice(this.copy.taskSidebarSelectedTaskMissingNotice); return content;} lines[task.lineNumber]=updater(lines[task.lineNumber]); return lines.join("\n");}); await this.refreshTasks(); }
  private formatDuration(startToken:string,doneToken:string){ const s=Date.parse(startToken.replace(/^@start\(|\)$/g,"")); const d=Date.parse(doneToken.replace(/^@done\(|\)$/g,"")); if(Number.isNaN(s)||Number.isNaN(d)||d<s) return ""; const h=Math.floor((d-s)/3600000); const m=Math.floor(((d-s)%3600000)/60000); return `duration ${h}h ${m}m`; }
  private async openTask(task:SidebarTask){ await this.app.workspace.openLinkText(task.file.path,"",false); this.app.workspace.getActiveViewOfType(MarkdownView)?.editor.setCursor({line:task.lineNumber,ch:0}); }
  private getPriorityLabel(p:PriorityFilter){return p==="urgent"?this.copy.taskSidebarPriorityUrgent:p==="high"?this.copy.taskSidebarPriorityHigh:p==="medium"?this.copy.taskSidebarPriorityMedium:p==="low"?this.copy.taskSidebarPriorityLow:this.copy.taskSidebarPriorityNone;}
  private get copy(){return getSettingsCopy(this.plugin.settings);} }

class TaskCommentModal extends Modal{ private comment=""; constructor(app:App, private readonly plugin:TaskManagerPlugin, private readonly onSubmit:(c:string)=>Promise<void>){super(app);} onOpen(){const copy=getSettingsCopy(this.plugin.settings); this.setTitle(copy.taskSidebarAddCommentTitle); new Setting(this.contentEl).setName(copy.taskSidebarCommentName).addTextArea(t=>t.onChange(v=>this.comment=v)); new Setting(this.contentEl).addButton(b=>b.setButtonText(copy.archiveCancelButton).onClick(()=>this.close())).addButton(b=>b.setButtonText(copy.taskSidebarAddComment).setCta().onClick(()=>{const c=this.comment.trim(); if(!c){new Notice(copy.taskSidebarCommentEmptyNotice); return;} void this.onSubmit(c).then(()=>this.close());}));} onClose(){this.contentEl.empty();}}
